In [3]:
import pandas as pd, numpy as np

In [6]:
# playing with a DataFrame
df=pd.DataFrame(np.arange(0,20).reshape(4,5),index=['row1','row2','row3','row4'],columns=['col1','col2','col3','col4','col5'])
df.head() #index - # of rows, columns- # of columns

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [7]:
df1=pd.DataFrame(np.arange(10,30).reshape(5,4), index=['r1','r2','r3','r4','r5'],columns=['col1','col2','col3','col4'])
df1.head()

col1  col2  col3  col4
r1    10    11    12    13
r2    14    15    16    17
r3    18    19    20    21
r4    22    23    24    25
r5    26    27    28    29

In [8]:
df.to_csv("test1_krish.csv")

In [6]:
# collections of series or rows or columns is a dataFrame

# a single row or a column in a DataFrame is a Series 

In [9]:
# accessing the elements 
df.loc['row1'] # loc gives all the values in row r 

col1    0
col2    1
col3    2
col4    3
col5    4
Name: row1, dtype: int32

In [10]:
type(df.loc['row1'])

pandas.core.series.Series

In [11]:
df.iloc[0:2,0:2] # In R, index starts from 1 

col1  col2
row1     0     1
row2     5     6

In [12]:
type(df.iloc[0:2,0:2])

pandas.core.frame.DataFrame

In [13]:
df.iloc[0:2,0:1]

col1
row1     0
row2     5

In [14]:
type(df.iloc[0:2,0:1]) # also a dataframe

pandas.core.frame.DataFrame

In [15]:
type(df.iloc[0:2,0]) #only rows, and 2 column 

pandas.core.series.Series

In [16]:
df.iloc[0:2,0]

row1    0
row2    5
Name: col1, dtype: int32

In [17]:
# Take the elements from the column 2 only 
df.iloc[:,1:2]

col2
row1     1
row2     6
row3    11
row4    16

In [18]:
# Take all elements except first column 
df.iloc[:,1:]

col2  col3  col4  col5
row1     1     2     3     4
row2     6     7     8     9
row3    11    12    13    14
row4    16    17    18    19

In [19]:
# convert df into array 
df.iloc[:,1:].values #.values converts df data into array

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [20]:
df.iloc[:,1:].values.shape

(4, 4)

In [21]:
# check for all null values columnwise 
df.isnull().sum() 

col1    0
col2    0
col3    0
col4    0
col5    0
dtype: int64

In [22]:
# get unique value counts from kth column
df['col1'].value_counts()

col1
0     1
5     1
10    1
15    1
Name: count, dtype: int64

In [23]:
df.col1.unique()

array([ 0,  5, 10, 15])

In [24]:
df.col2.unique()

array([ 1,  6, 11, 16])

In [25]:
# access column directly 
df['col3']

row1     2
row2     7
row3    12
row4    17
Name: col3, dtype: int32

In [26]:
type(df['col3'])

pandas.core.series.Series

In [27]:
df[['col2','col3']]

col2  col3
row1     1     2
row2     6     7
row3    11    12
row4    16    17

In [28]:
type(df[['col2','col3']])

pandas.core.frame.DataFrame

In [29]:
df[['col1','col4']]

col1  col4
row1     0     3
row2     5     8
row3    10    13
row4    15    18